import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import { getServerSession } from "@/lib/session";
import { Navbar } from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body
        className={inter.className + "min-w-screen min-h-screen dark relative"}
      >
        <Provider>
          <div className="flex bg-slate-950">
            <Navbar user={session?.user} />
            <div className="flex flex-grow p-1">{children}</div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
